# -*- coding: utf-8 -*-
"""FinalExamReview2LK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNc55OahJ5fg9OGhYkFPoj9qAdW2LMNs
"""

#Q1
#For the first one it will return 10 and the other one 15

#Q2
x = [1,2,4,5,6,7,8,10]
new_x = []
i = 0
while i != len(x):
  new_x.append(x[i])
  i = i + 2
print(new_x)

#Other method

new_x1 = x[0::2]
print(new_x1)

#Q3
#It will print this List: [6,7,8]

#Q4
nested = [[1,2,3],[4,5,6],[7,8,9]]
nested_1 = [i[1:] for i in nested]
print(nested_1[1])

#Q5
nested = [[1,2,3],[4,5,6],[7,8,9]]
new_x = [i[::-1] for i in nested]
print(new_x)

# new_x1 = nested[::-1]
# print(new_x1)

#Q6
words = ["Deep","fried","wings"]
words = '-'.join(words)
print(words)

#Q7
text = "The beach is beautiful, and spending time at beach is always enjoyable!"
substring = "beach"
List = text.split()
for i in range(len(List)-1,-1,-1):
  if substring == List[i]:
    print(f"the Last occurence of the word '{substring}' is in position: {i}")
    substring = ''

number_str = '00012345'
print(number_str.strip('0'))

text =['Line1','Line2','Line3']
text1 = ''
for i in text:
  text1 = text1 + i + '\n'
print(text1)

weight = float(input("Enter your weight (in Kg): "))
height = float(input("Enter your height (in m): "))
BMI = weight/(height)**2
if BMI > 25:
  print(f"Your BMI is: {BMI} so you are overweight...")
else:
  print(f"Your BMI is: {BMI} so ou are not overweight!")