# -*- coding: utf-8 -*-
"""FinalExamReviewLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRAaYyoK9bISuO3P0SZZ5rL54Z9jehQC
"""

#Q1
date_string = '11/26/2020'
print(f"The year is: {date_string.split('/')[-1]}")

#Q2
a = [1, 2, 0, 3]
b = [3, 4, 6, 5]
total = 0
j = 0
for i in a:
    if i != 0:
      total = total + i*b[j]
    j = j + 1
print(f"The Total is: {total}")

#Q3
sentence = "apple banana apple orange banana apple"
new_set = set(sentence.split())
List = sentence.split()
Total = 0
for i in new_set:
  for j in List:
    if i == j:
      Total = Total + 1
  print(f"The occurrences for the word {i} is: {Total}")
  Total = 0

#Q4
text = "Hello, World!"
vowel = "aeiouAEIOU"
vowels = ['a','e','i','o','u','A','E','I','O','U']

def main(sentence):
  for i in sentence:
    for j in vowels:
      if i == j:
        sentence = sentence.replace(j,'@')
  return sentence

print(main(text))
print(main(vowel))

#Q5
sentence = "it's raining cats and dogs."
List = sentence.split()
new_sentence = ''
for i in List:
  i = i.replace(i[0],i[0].upper())
  new_sentence = new_sentence + ' ' + i
print(new_sentence)

#Q6
sentence = "Chicago is very different from Boston"
List = sentence.split()
longest = List[0]
for i in List:
  if len(i) > len(longest):
    longest = i
print(f"The longest word in this sentence is: {longest}")

#Q7
text = "Python 3.9 is great for 2024!"
new_text = ''
for i in text:
  if i.isdigit() == True:
    new_text = new_text
  else:
    new_text = new_text + i
print(new_text)

#Q8
text = "Hello World! Python3"
upper = 0
lower = 0
digits = 0
for i in text:
  if i.isdigit() == True:
    digits = digits + 1
  elif i.isupper() == True:
    upper = upper + 1
  elif i.islower():
    lower = lower + 1
print(f"The number of uppercase letters in this sentence is: {upper}")
print(f"The number of lowercase letters in this sentence is: {lower}")
print(f"The number of digits in this sentence is: {digits}")

#Q9
str1 = "listen"
str2 = "silent"
set1 = list(set(str1))
set2 = list(set(str2))
k = 0
for i in set1:
  for j in set2:
    if i == j:
      k = k + 1
if k == len(str1):
  print(f"{str1} and {str2} are anagrams.")
else:
  print(f"{str1} and {str2} aren't anagrams.")

#Q10
# Initial inventory
inventory = {
    "apple": 10,
    "banana": 5,
    "orange": 8
}

# List of items sold
sold_items = ["apple", "banana", "grape", "apple", "orange", "banana"]

for i in sold_items:
  for key,value in inventory.items():
    if key == i and value !=0:
      inventory[key] = value - 1
print(inventory)